# ============================================================
# report_generator.py
# Health Report Generator
# AI Health Symptom Checker - THINK CHAMP PVT LTD
# ============================================================

import os
from datetime import datetime

REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'reports')
os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_report(result: dict) -> str:
    """
    Generate a downloadable health report as a .txt file.
    Returns the filename of the saved report.
    """
    timestamp   = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename    = f"health_report_{timestamp}.txt"
    report_path = os.path.join(REPORTS_DIR, filename)

    symptoms_str = ', '.join([s.replace('_', ' ').title() for s in result.get('symptoms_entered', [])])
    now_str      = datetime.now().strftime('%d %B %Y, %I:%M %p')

    report_content = f"""
╔══════════════════════════════════════════════════════════════╗
║          AI HEALTH SYMPTOM CHECKER - HEALTH REPORT           ║
║                   THINK CHAMP PVT LTD                        ║
╚══════════════════════════════════════════════════════════════╝

Report Generated  : {now_str}
Report ID         : {timestamp}

──────────────────────────────────────────────────────────────
  SYMPTOMS ENTERED
──────────────────────────────────────────────────────────────
{symptoms_str if symptoms_str else 'None entered'}

──────────────────────────────────────────────────────────────
  PREDICTION RESULT
──────────────────────────────────────────────────────────────
Possible Condition : {result.get('disease', 'N/A')}
Confidence Score   : {result.get('confidence', 0)}%
Model Accuracy     : {result.get('model_accuracy', 'N/A')}%

──────────────────────────────────────────────────────────────
  AI HEALTH RECOMMENDATION
──────────────────────────────────────────────────────────────
{result.get('recommendation', 'Please consult a healthcare professional.')}

──────────────────────────────────────────────────────────────
  ⚠  MEDICAL DISCLAIMER
──────────────────────────────────────────────────────────────
This report is generated by an AI-based educational project and
is NOT a substitute for professional medical advice, diagnosis,
or treatment. Always consult a qualified healthcare professional
for proper medical guidance.

──────────────────────────────────────────────────────────────
  EMERGENCY CONTACTS
──────────────────────────────────────────────────────────────
National Health Helpline (India) : 104
Emergency                        : 112
COVID-19 Helpline                : 1075

──────────────────────────────────────────────────────────────
           © THINK CHAMP PVT LTD — Internship Project
──────────────────────────────────────────────────────────────
"""

    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_content)

    # Also overwrite the static health_report.txt
    static_path = os.path.join(REPORTS_DIR, 'health_report.txt')
    with open(static_path, 'w', encoding='utf-8') as f:
        f.write(report_content)

    return filename
